#%RAML 1.0
title: PROGRAMATOR.SK
version: v1
baseUri: http://api.programator.sk/

mediaType: application/json

/gallery:
  description: Práca s galériami
  get:
    description: |
      Zoznam všetkých galérií. Response obsahuje pole objektov galérií,
      kde `path` je cesta priamo použiteľná pre získanie obsahu galérie
      a `name` je názov galérie.

      Ak galéria obsahuje obrázok, tak tento je v objekte ako `image`
    responses:
      200:
        body:
          application/json:
            type: !include schemas/gallery_list.json
            example: |
              {
                "galleries": [
                  {
                    "path": "Wild%20Nature",
                    "name": "Wild Nature"
                  },
                  {
                    "path": "Cars",
                    "name": "Cars"
                  }
                ]
              }
      500:
        description: Nedefinovaná chyba
  post:
    description: |
      Vytvorenie novej galérie. Názov galérie nemôže obsahovať znak `/`
    body:
      application/json:
        type: !include schemas/gallery_insert.json
        example: |
          {
            "name": "Wild animals"
          }
    responses:
      201:
        description: Galeria bola vytvorená
        body:
          application/json:
            example: |
              {
                "path": "Animals",
                "name": "Animals"
              }
      400:
        description: Chybne zadaný request - nevhodný obsah podľa schémy.
        body:
          application/json:
            description: Detail chyby.
            example: |
              {
                "code": 400,
                "payload": {
                  "paths": ["name"],
                  "validator": "required",
                  "example": null
                },
                "name": "INVALID_SCHEMA",
                "description": "Bad JSON object: u'name' is a required property"
              }
      409:
        description: Galéria so zadaným názvom už existuje
      500:
        description: Nedefinovaná chyba
  /{path}:
    get:
      description: Zoznam obrázkov v galérii.
      responses:
        200:
          description: |
            Zoznam obrázkov v galérii a informácie o galérii.
          body:
            application/json:
              type: !include schemas/gallery_detail.json
              example: |
                {
                  "gallery": {
                    "path": "Animals",
                    "name": "Animals"
                  },
                  "images": [
                    {
                      "path": "elephant.jpg",
                      "fullpath": "Animals/elephant.jpg",
                      "name": "Elephant",
                      "modified": "2017-04-19T08:11:00.0+0200"
                    },
                    {
                      "path": "lion.jpg",
                      "fullpath": "Animals/lion.jpg",
                      "name": "Lion",
                      "modified": "2017-04-19T08:11:32.0+0200"
                    }
                  ]
                }
        404:
          description: Zvolená galéria neexistuje
        500:
          description: Nedefinovaná chyba
    delete:
      description: Vymazanie zvolenej galérie, alebo obrázku
      responses:
        200:
          description: Galéria/obrázok bola úspešne vymazaná
        404:
          description: Zvolená galéria/obrázok neexistuje
        500:
          description: Nedefinovaná chyba
    post:
      description: Upload obrázku do zvolenej galérie
      headers:
        Content-Type:
          type: string
          required: true
          example: |
            Content-Type: multipart/form-data; boundary=--boundary
      body:
        multipart/form-data:
          description: |
            Upload obrázku do zvolenej galérie.
            Je mozne uploadnut naraz viac obrazkov. API spracuje kazdy typ image/jpeg.
            Request je klasický file multipart/form-data upload.
            Ako názov obrázku sa použije filename. Ak už súbor s týmto názvom v galérii existuje,
            zmení sa mu názov, pridaním čísla na koniec názvu.
          type: file
          fileTypes: ["image/jpeg"]
          example: |
            ----boundary
            Content-Disposition: form-data; name="image"; filename="elephant.jpg"
            Content-Type: image/jpeg

            <encoded document>

            ----boundary--
      responses:
        201:
          body:
            application/json:
              example: |
                {"uploaded": [{
                  "path": "elephant.jpg",
                  "fullpath": "Animals/elephant.jpg",
                  "name": "Elephant",
                  "modified": "2017-04-19T08:11:00+0200"
                }]}
        400:
          description: Chybný request - nenašiel sa súbor pre upload.
        404:
          description: Galéria pre upload sa nenašla
/images:
  description: Práca s obrázkami
  /{w}x{h}/{path}:
    uriParameters:
      w:
        type: number
        description: |
          Požadovaná šírka obrázku. Môže byť 0, vtedy sa dopočíta
          podľa výšky so zachovaním pomeru strán.
      h:
        type: number
        description: |
          Požadovaná šírka obrázku. Môže byť 0, vtedy sa dopočíta
          podľa šírky so zachovaním pomeru strán.
      path:
        type: string
        description: |
          `fullpath` parameter so zoznamu obrázkov `GET /gallery/{path}`
    get:
      description: Vygenerovanie náhľadového obrázku
      responses:
        200:
          body:
            image/jpeg:
        404:
          description: Obrázok sa nenašiel
        500:
          description: Nepodarilo sa spracovať obrázok a vygenerovať náhľad.
